export const AUTH_USER_TYPES ={
    LOGIN_USER:'LOGIN_USER',
    LOGOUT_USER:'LOGOUT_USER',
}
export const USER_TYPES ={
    SET_USER:'SET_USER',
    REMOVE_USER:'REMOVE_USER',
    UPDATE_USER:'UPDATE_USER'
}

export const STORE_TYPES ={
    GET_ITEMS:'GET_ITEMS',
    UPDATE_ITEM:'UPDATE_ITEM',
}