apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactions-aks-demo
spec:
  selector:
    matchLabels:
      app: ctse-assignment-frontend
  template:
    metadata:
      labels:
        app: ctse-assignment-frontend
    spec:
      containers:
        - name: ctse-assignment-frontend
          image: mdilankan/ctse-assignment-frontend
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000