name: ci

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        run: docker login --username '${{secrets.DOCKERHUB_USERNAME}}' --password '${{secrets.DOCKERHUB_TOKEN}}'
      -
        name: Build docker image
        run: docker build -t '${{secrets.DOCKERHUB_USERNAME}}'/ctse-assignment-frontend:'${{github.sha}}' .
      -
        name: push docker image
        run: docker push '${{secrets.DOCKERHUB_USERNAME}}'/ctse-assignment-frontend:'${{github.sha}}'  
      - 
        name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1
        with:
          # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
          creds: '${{secrets.AZURE_CREDENTIALS}}'
          # Resource Group Name
          resource-group: ctse-project
          # AKS Cluster Name
          cluster-name: ctse-project-frontend
      # Create K8s secrets to pull images
      - name: Create secret in Kubernetes cluster
        uses: Azure/k8s-create-secret@v1.1
        with:
          # Container registry url
          container-registry-url: https://index.docker.io/v1/
          # Container registry username
          container-registry-username: '${{secrets.DOCKERHUB_USERNAME}}'
          # Container registry password
          container-registry-password: '${{secrets.DOCKERHUB_TOKEN}}'
          # Type of Kubernetes secret. For example, docker-registry or generic
          secret-type: docker-registry
          # Name of the secret. You can use this secret name in the Kubernetes YAML configuration file.
          secret-name: docker-image-pull-secret

        # Deploy to k8s cluster
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1
        with:
          # Path to the manifest files which will be used for deployment.
          manifests: |
            k8s/deployment.yml
            k8s/service.yml
          # Fully qualified resource URL of the image(s) to be used for substitutions on the manifest files Example: contosodemo.azurecr.io/helloworld:test
          images: '${{secrets.DOCKERHUB_USERNAME}}/ctse-assignment-frontend:${{github.sha}}'
          # Name of a docker-registry secret that has already been set up within the cluster. Each of these secret names are added under imagePullSecrets field for the workloads found in the input manifest files
          imagepullsecrets: docker-image-pull-secret
          # deploy/promote/reject
          action: deploy

