name: ci

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        run: docker login --username '${{secrets.DOCKERHUB_USERNAME}}' --password '${{secrets.DOCKERHUB_TOKEN}}'
      -
        name: Build docker image
        run: docker build -t '${{secrets.DOCKER_LOGIN}}'/ctse-assignment-frontend:'${{github.sha}}'
      -
        name: push docker image
        run: docker push '${{secrets.DOCKER_LOGIN}}'/ctse-assignment-frontend:'${{github.sha}}'
